AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack for EC2, S3 with CloudFront, and temporary user

Parameters:
  TempUserName:
    Type: String
    Description: Name for the temporary user
  TempUserPolicyName:
    Type: String
    Description: Name for the temporary user's policy

Resources:
  TESTS3001:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-tests3001-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  TESTS3001BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TESTS3001
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt TESTS3001.Arn
              - !Sub ${TESTS3001.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  TESTCFD001:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: TESTS3001
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
        Enabled: true
        Origins:
          - DomainName: !GetAtt TESTS3001.RegionalDomainName
            Id: TESTS3001
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${TESTCFD001OriginAccessIdentity}
        Restrictions:
          GeoRestriction:
            Locations: 
              - IN
            RestrictionType: whitelist

  TESTCFD001OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref TESTS3001

  TESTCFD001TESTS3001Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TESTS3001
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt TESTCFD001OriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub ${TESTS3001.Arn}/*
            
  TESTSG001:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH for User
      GroupName: AllowSSH
      VpcId: vpc-04aaa21271ac4b8ae
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          
  TESTSG002:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow VITE access for Web
      GroupName: AllowVITE
      VpcId: vpc-04aaa21271ac4b8ae
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 5173
          ToPort: 5173
          IpProtocol: tcp

  TESTEC2001:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b70fa74e45c3917
      SecurityGroupIds:
        - !GetAtt TESTSG001.GroupId
        - !GetAtt TESTSG002.GroupId

  TempUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref TempUserName

  TempUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TempUser

  TempUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref TempUserPolicyName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !GetAtt TESTS3001.Arn
          - Effect: Allow
            Action:
              - cloudfront:GetDistribution
            Resource: '*'
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:StartInstances
              - ec2:StopInstances
            Resource: '*'
      Users:
        - !Ref TempUser

Outputs:
  EC2InstanceId:
    Description: ID of the EC2 instance
    Value: !Ref TESTEC2001
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref TESTS3001
  CloudFrontDistributionId:
    Description: ID of the CloudFront distribution
    Value: !Ref TESTCFD001
  TempUserAccessKeyId:
    Description: Access key ID for the temporary user
    Value: !Ref TempUserAccessKey
  TempUserSecretAccessKey:
    Description: Secret access key for the temporary user
    Value: !GetAtt TempUserAccessKey.SecretAccessKey